name: this is my pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: print message
        run: echo "hy my name is sharik"

      - name: check user
        run: whoami

      - name: check storage
        run: df -Th
